# Generated by Django 4.2.10 on 2024-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('phone', models.CharField(max_length=25, unique=True)),
                ('hidden_field', models.CharField(max_length=4)),
            ],
        ),
    ]
